# Generated by Django 3.1 on 2020-11-15 14:44

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201115_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
